### ISSUE TITLE
Syntax

### ISSUE THREAD

**Issue by AlexMorello** [sunenj/MP-PCA-Denoising#4]
Dear Professor Jespersen,

May you please illuminate me as to the proper syntax? I've tried -h to no avail, nor do the readme files contain any user guide.

Many thanks in advance,
Alex

**Comment by AlexMorello** [comment]
Professor Jespersen? @sunenj

**Comment by Neurophysics-CFIN** [comment]
Hi Alex,
in matlab you can write "help denoise.m" and it will show you the usage. Or open the script, and see: function [denoised,S2,P] = denoise(image,window,mask)
% MP-PCA denoising
%
% input:
% image:  images to be denoised. Must have 3 or 4 indices with MRI images 
%         along the last index and voxels in the first 2 or 3.
% window: sliding window
% mask:   is true for all voxels per default but can be manually set to
%         mask out regions.
%
% output:
% denoised: denoised images
% S2:       map of estimated noise variance
% P:        number of detected signal principal components

Hope this helps.
Sune
